### ISSUE TITLE
Can't figure it out. an error occurs when you click request

### ISSUE THREAD

**Issue by Gy9vin** [VISCHub/vet-faucet#14]
in the log that this error can not understand what the problem is

> 0 info it worked if it ends with ok
> 1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
> 2 info using npm@5.6.0
> 3 info using node@v9.11.1
> 4 verbose run-script [ 'prestart', 'start', 'poststart' ]
> 5 info lifecycle Vet-network-faucet@1.0.0~prestart: Vet-network-faucet@1.0.0
> 6 info lifecycle Vet-network-faucet@1.0.0~start: Vet-network-faucet@1.0.0
> 7 verbose lifecycle Vet-network-faucet@1.0.0~start: unsafe-perm in lifecycle true
> 8 verbose lifecycle Vet-network-faucet@1.0.0~start: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/var/www/vet-faucet/faucet/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin$
> 9 verbose lifecycle Vet-network-faucet@1.0.0~start: CWD: /var/www/vet-faucet/faucet
> 10 silly lifecycle Vet-network-faucet@1.0.0~start: Args: [ '-c', 'node index.js' ]
> 11 silly lifecycle Vet-network-faucet@1.0.0~start: Returned: code: 1  signal: null
> 12 info lifecycle Vet-network-faucet@1.0.0~start: Failed to exec start script
> 13 verbose stack Error: Vet-network-faucet@1.0.0 start: `node index.js`
> 13 verbose stack Exit status 1
> 13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
> 13 verbose stack     at EventEmitter.emit (events.js:180:13)
> 13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
> 13 verbose stack     at ChildProcess.emit (events.js:180:13)
> 13 verbose stack     at maybeClose (internal/child_process.js:936:16)
> 13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
> 14 verbose pkgid Vet-network-faucet@1.0.0
> 15 verbose cwd /var/www/vet-faucet/faucet
> 16 verbose Linux 2.6.32-042stab120.18
> 17 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
> 18 verbose node v9.11.1
> 19 verbose npm  v5.6.0
> 20 error code ELIFECYCLE
> 21 error errno 1
> 22 error Vet-network-faucet@1.0.0 start: `node index.js`
> 22 error Exit status 1
> 23 error Failed at the Vet-network-faucet@1.0.0 start script.
> 23 error This is probably not a problem with npm. There is likely additional logging output above.
> 24 verbose exit [ 1, true ]

**Comment by vietlq** [comment]
Ok I'll have a look. Thanks for reporting
